### ISSUE TITLE
start_date parsing + data quality 

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/pa-global-monitoring#37]
More of a data quality issue that i think we should just flag up probably. But documenting it here:

I was looking at the cholera data and noticed that all `start_date` for `week_date`  `2023-09-25` was not properly parsing. I noticed this is because the `start_of_reporting_period` format changed. Should we just flag this to the team doing the scraping?

Digging a bit more into the `start_of_reporting_period` I do see that the formatting does change quite a bit over time (either `dmy` or `mdy`), therefore the code here either fails to parse some records  or in some cases likely parses incorrectly.

https://github.com/OCHA-DAP/pa-global-monitoring/blob/2c05b5bd038bf72e664689234a88c89583773c11/src/indicators/cholera/update_cholera.R#L50-L55

there would be a light cleaning step to where we could adjust the above w/ a conditional `dmy()` or `mdy()` based on the values (i.e months can't be >12) ... but this wouldn't ensure they were all correct.

**Comment by caldwellst** [comment]
Sadly, nothing the scraping team can do, because if you look at the bulletins, they are just switching the way the date is recorded in the system. Madness.

Basically ,from the 25th of September, their bulletins primarily use the new format of `mdy`, which is stored as `9/25/2023`. for instance. However, their previous format was `25-Sep-2023`.
